---
- name: Use local apt-cache-ng
  lineinfile: "dest=/etc/apt/apt.conf create=yes insertafter=EOF line='Acquire::http { Proxy \"{{apt_cache_ng_url}}\"; };'"
  sudo: yes
  when: apt_cache_ng_url is defined

- name: set locale to $locale
  command: /usr/sbin/update-locale LANG={{locale}} LC_ALL={{locale}}
  sudo: yes
  when: ansible_env.LANG != "{{locale}}"

- name: check /etc/timezone
  command: cat /etc/timezone
  register: cat_etc_timezone
  changed_when: false

- name: set /etc/localtime to $timezone
  command: /bin/cp /usr/share/zoneinfo/{{timezone}} /etc/localtime
  sudo: yes
  when: cat_etc_timezone.stdout != "{{timezone}}"

- name: set /etc/timezone to $timezone
  lineinfile: dest=/etc/timezone regexp=^UTC$ line='{{timezone}}'
  sudo: yes
  notify: update tzdata
  when: cat_etc_timezone.stdout != "{{timezone}}"

# Don't update cache if less than an hour old
- name: apt-get update
  apt: update_cache=yes cache_valid_time=3600
  sudo: yes

- name: Append deploy to /etc/hosts
  lineinfile: dest=/etc/hosts insertafter=EOF line='192.168.42.10   deploy'
  sudo: yes

- name: Append node1 to /etc/hosts
  lineinfile: dest=/etc/hosts insertafter=EOF line='192.168.42.11   node1'
  sudo: yes

- name: Append node2 to /etc/hosts
  lineinfile: dest=/etc/hosts insertafter=EOF line='192.168.42.12   node2'
  sudo: yes

- name: Append node3 to /etc/hosts
  lineinfile: dest=/etc/hosts insertafter=EOF line='192.168.42.13   node3'
  sudo: yes

- name: Create ceph user
  # Created with: openssl passwd -1 ceph
  # TODO Turn into variable
  user: name=ceph password=$1$DmCVnC7z$qnW1sqRIKfLQp7jK3g3Uq0
  sudo: yes

- name: Enable password-less sudo for ceph user
  lineinfile: "line='ceph ALL = (root) NOPASSWD:ALL' dest=/etc/sudoers.d/ceph create=yes"
  sudo: yes

- name: chmod 0440 /etc/sudoers.d/ceph
  file: name=/etc/sudoers.d/ceph mode=0440
  sudo: yes

