---
- name: Install python & required packages
  apt: pkg={{ item }} state=installed
  with_items:
   - python-mock
   - python-configobj
   - python-support
   - python-pip
   - python-virtualenv
   - python-pycurl
  sudo: yes

- name: Add Ceph Key
  apt_key: url={{ ceph.apt_key }} state=present
  sudo: yes

- name: apt-key update
  command: apt-key update
  sudo: yes

- name: Add Ceph Repo
  apt_repository: "repo={{item}} state=present"
  with_items:
    - 'deb http://ceph.com/debian-{{ ceph.ceph_release }}/ {{ distro_release }} main'
    - 'deb http://ceph.com/packages/ceph-extras/debian {{ distro_release }} main'
  notify: apt-get update
  sudo: yes

- name: Install Ceph packages
  apt: pkg={{ item }} state=installed
  environment: proxy_env
  with_items:
    - ceph-deploy
    - ceph
    - ceph-mds
    - ceph-common
    - ceph-fs-common
    - gdisk
    - tgt
  sudo: yes

- name: mkdir -p /home/{{ansible_user_id}}/my-cluster (as {{ansible_user_id}})
  file: path="/home/{{ansible_user_id}}/{{cluster_name}}" state=directory

