---
- name: Install python & required packages
  apt: pkg={{ item }} state=installed
  with_items:
   - python-mock
   - python-configobj
   - python-support
   - python-pip
   - python-virtualenv
   - python-pycurl
   - expect
  sudo: yes

- name: Create ceph user
  # Created with: openssl passwd -1 ceph
  # TODO Turn into variable
  user: name=ceph password=$1$DmCVnC7z$qnW1sqRIKfLQp7jK3g3Uq0
  sudo: yes

- name: Add Ceph Key
  apt_key: url={{ ceph.apt_key }} state=present
  sudo: yes

- name: apt-key update
  command: apt-key update
  sudo: yes

- name: Add ceph repo
  apt_repository: repo="deb http://ceph.com/debian-{{ ceph.ceph_release }}/ {{ distro_release }} main" state=present update_cache=yes
  sudo: yes

- name: Add ceph-extras repo
  apt_repository: repo="deb http://ceph.com/packages/ceph-extras/debian {{ distro_release }} main" state=present update_cache=yes
  sudo: yes

- name: Install Ceph packages
  apt: pkg={{ item }} state=installed
  environment: proxy_env
  with_items:
    - ceph-deploy
    - ceph
    - ceph-mds
    - ceph-common
    - ceph-fs-common
    - gdisk
  sudo: yes

- name: Install tgt packages
  apt: pkg=tgt state=installed
  environment: proxy_env
  sudo: yes

- name: whoami
  command: whoami
  register: w0
- debug: msg="whoami {{w0.stdout}}"

- name: whoami (sudo)
  command: whoami
  sudo: yes
  register: w1
- debug: msg="whoami {{w1.stdout}}"

- name: whoami (sudo + sudo_user)
  command: whoami
  sudo: yes
  sudo_user: ceph
  register: w2
- debug: msg="whoami {{w2.stdout}}"

- name: Run as ceph
  include: as_ceph.yml
  remote_user: "{{ansible_ssh_user}}"
  sudo: yes
  sudo_user: ceph
