---
- name: Install python & required packages
  apt: pkg={{ item }} state=installed
  with_items:
   - python-mock
   - python-configobj
   - python-support
   - python-pip
   - python-virtualenv
   - python-pycurl
  sudo: yes

- name: Add Ceph Key
  apt_key: url={{ ceph.apt_key }} state=present
  sudo: yes

- name: apt-key update
  command: apt-key update
  sudo: yes

- name: Add Ceph Repo
  apt_repository: "repo='deb http://ceph.com/debian-{{ ceph.ceph_release }}/ {{ distro_release }} main' state=present"
  register: add_ceph_repo
  sudo: yes

- name: Add Ceph Extras Repo
  apt_repository: "repo='deb http://ceph.com/packages/ceph-extras/debian {{ distro_release }} main' state=present"
  sudo: yes

- name: Update apt cache
  apt: update_cache=yes
  sudo: yes
  when: add_ceph_repo|changed

- name: Install Ceph packages
  apt: pkg={{ item }} state=installed
  environment: proxy_env
  with_items:
    - ceph-deploy
    - ceph
    - ceph-mds
    - ceph-common
    - ceph-fs-common
    - gdisk
    - tgt
  sudo: yes
