---
- hosts: deploy
  roles:
    - deploy

- hosts: node1
  roles:
    - mon
    - node

- hosts: node2:node3
  roles:
    - node
    - { role: osd, osd_dir: "osd{{ansible_hostname|replace('node','')}}" }
